words = [
    "alphanums",
    "artifact",
    "artifacts",
    "authorization",
    "autocommit",
    "ble",
    "cconj",
    "changethis",
    "clusterer",
    "cov",
    "dap",
    "dbscan",
    "decrypt",
    "dep",
    "doi",
    "dslim",
    "ent",
    "ents",
    "epsg",
    "fac",
    "fastapi",
    "fernet",
    "fzf",
    "geocoder",
    "geocoding",
    "geospacy",
    "geospacy's",
    "geospatial",
    "gnormal",
    "gpe",
    "gvisual",
    "hatchling",
    "httpx",
    "ipython",
    "issn",
    "kilometers",
    "kylechui",
    "lemmatizer",
    "mailhog",
    "maress",
    "matchers",
    "mbbill",
    "mkl",
    "nbf",
    "ner",
    "nfdi",
    "nlp",
    "noqa",
    "normalize",
    "normalized",
    "norp",
    "nsew",
    "omp",
    "onupdate",
    "orchestrator",
    "polyfactory",
    "propn",
    "psycopg",
    "punct",
    "pwdlib",
    "pycountry",
    "pydantic",
    "pyproject",
    "pyright",
    "sconj",
    "sentencizer",
    "sents",
    "spacy",
    "sqlmodel",
    "studysite",
    "systemctl",
    "testability",
    "textcat",
    "uselist",
    "utm",
    "viewbox",
    "wgs",
    "winblend",
    "zot",
    "zotero",
    'ﬁ":',
    'ﬃ":',
    'ﬄ":',
]
use_global = true
